version: '3'
services:
  db:
    image: 'mongo:latest'
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - ./db/data/mongo:/data/db
    env_file: .env
    restart: unless-stopped

  proxy:
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    container_name: proxy
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
